-- ============================================================
-- WORKNEST WHATSAPP CHATBOT DATABASE SCHEMA
-- ============================================================

-- ============================================================
-- 1. WHATSAPP CONTACTS
-- ============================================================

create table if not exists whatsapp_contacts (
    id bigint generated by default as identity primary key,

    phone_number text not null unique,

    name text,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


create index if not exists idx_whatsapp_contacts_phone
on whatsapp_contacts(phone_number);


-- ============================================================
-- 2. WHATSAPP CONVERSATIONS
-- ============================================================

create table if not exists whatsapp_conversations (
    id bigint generated by default as identity primary key,

    contact_id bigint not null
        references whatsapp_contacts(id)
        on delete cascade,

    status text not null default 'open'
        check (
            status in (
                'open',
                'closed'
            )
        ),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


create index if not exists idx_whatsapp_conversations_contact
on whatsapp_conversations(contact_id);

create index if not exists idx_whatsapp_conversations_status
on whatsapp_conversations(status);

create index if not exists idx_whatsapp_conversations_updated
on whatsapp_conversations(updated_at);


-- ============================================================
-- 3. WHATSAPP MESSAGES
-- ============================================================

create table if not exists whatsapp_messages (
    id bigint generated by default as identity primary key,

    conversation_id bigint not null
        references whatsapp_conversations(id)
        on delete cascade,

    whatsapp_message_id text,

    direction text not null
        check (
            direction in (
                'incoming',
                'outgoing'
            )
        ),

    message_type text not null default 'text',

    message_text text,

    created_at timestamptz not null default now()
);


create index if not exists idx_whatsapp_messages_conversation
on whatsapp_messages(conversation_id);

create index if not exists idx_whatsapp_messages_created
on whatsapp_messages(created_at);

create index if not exists idx_whatsapp_messages_direction
on whatsapp_messages(direction);


-- Prevent duplicate WhatsApp webhook messages
create unique index if not exists idx_whatsapp_messages_message_id
on whatsapp_messages(whatsapp_message_id)
where whatsapp_message_id is not null;


-- ============================================================
-- 4. COMPLAINTS
-- ============================================================

create table if not exists complaints (
    id bigint generated by default as identity primary key,

    complaint_id text not null unique,

    contact_id bigint
        references whatsapp_contacts(id)
        on delete set null,

    conversation_id bigint
        references whatsapp_conversations(id)
        on delete set null,

    complaint text not null,

    category text,

    status text not null default 'open'
        check (
            status in (
                'open',
                'in_progress',
                'resolved',
                'closed'
            )
        ),

    is_followup boolean
        not null default false,

    previous_complaint_id text,

    -- --------------------------------------------------------
    -- Resolved notification tracking
    -- --------------------------------------------------------

    resolved_notification_sent boolean
        not null default false,

    resolved_notification_sent_at timestamptz,

    -- --------------------------------------------------------
    -- Customer response to resolved complaint
    --
    -- Possible values:
    --   resolved
    --   persists
    --   auto_closed
    -- --------------------------------------------------------

    resolution_response text
        check (
            resolution_response is null
            or resolution_response in (
                'resolved',
                'persists',
                'auto_closed'
            )
        ),

    resolution_response_at timestamptz,

    -- --------------------------------------------------------
    -- Automatically close complaint after 24 hours
    -- if customer does not respond.
    -- --------------------------------------------------------

    auto_close_at timestamptz,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);

alter table complaints
    add column if not exists is_followup boolean
        not null default false;

alter table complaints
    add column if not exists previous_complaint_id text;


-- ============================================================
-- COMPLAINT INDEXES
-- ============================================================

create index if not exists idx_complaints_complaint_id
on complaints(complaint_id);

create index if not exists idx_complaints_contact
on complaints(contact_id);

create index if not exists idx_complaints_conversation
on complaints(conversation_id);

create index if not exists idx_complaints_status
on complaints(status);

create index if not exists idx_complaints_created
on complaints(created_at);

create index if not exists idx_complaints_auto_close
on complaints(auto_close_at);

create index if not exists idx_complaints_followup
on complaints(is_followup, previous_complaint_id);


-- ============================================================
-- 5. HELPFUL INDEX FOR RESOLVED COMPLAINT RESPONSES
-- ============================================================

create index if not exists idx_complaints_waiting_resolution
on complaints(
    contact_id,
    status,
    resolved_notification_sent,
    resolution_response
);

-- Dashboard login users. Store PBKDF2 hashes, never plaintext passwords.
create table if not exists dashboard_users (
    id bigint generated by default as identity primary key,
    user_name text not null unique,
    password_salt text not null,
    password_hash text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_name = 'dashboard_users'
          and column_name = 'email'
    ) and not exists (
        select 1
        from information_schema.columns
        where table_name = 'dashboard_users'
          and column_name = 'user_name'
    ) then
        alter table dashboard_users rename column email to user_name;
    end if;
end $$;


-- ============================================================
-- 6. COMMENTS / DOCUMENTATION
-- ============================================================

comment on table whatsapp_contacts is
'WhatsApp customers/contacts interacting with WorkNest.';

comment on table whatsapp_conversations is
'WhatsApp conversations belonging to WorkNest contacts.';

comment on table whatsapp_messages is
'Incoming and outgoing WhatsApp messages.';

comment on table complaints is
'WorkNest customer complaints submitted through WhatsApp.';


comment on column complaints.resolved_notification_sent is
'Indicates whether the resolved complaint notification was successfully sent to the customer.';

comment on column complaints.resolved_notification_sent_at is
'Timestamp when the resolved notification was successfully sent.';

comment on column complaints.resolution_response is
'Customer response after complaint was marked resolved: resolved, persists, or auto_closed.';

comment on column complaints.resolution_response_at is
'Timestamp when the customer responded to the resolved complaint.';

comment on column complaints.auto_close_at is
'Timestamp after which a resolved complaint can be automatically closed if the customer does not respond.';


-- ============================================================
-- END OF SCHEMA
-- ============================================================